const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url,opt={}){const r=await fetch(url,{credentials:"same-origin",...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});if(r.status===401)showLogin();const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
function showLogin(){$("#loginBox").hidden=false;$("#dash").hidden=true}function showDash(){$("#loginBox").hidden=true;$("#dash").hidden=false;load()}
async function me(){try{await api("/api/admin/me");showDash()}catch{showLogin()}}
$("#login").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({username:f.get("username"),password:f.get("password")})});showDash()}catch(err){$("#loginMsg").textContent=err.message}})
$("#logout").addEventListener("click",async()=>{await api("/api/admin/logout",{method:"POST"});showLogin()});
async function load(){const d=await api("/api/admin/dashboard");$("#pending").textContent=d.pending.length;$("#published").textContent=d.published.length;$("#queue").innerHTML=d.pending.length?d.pending.map((j,i)=>`<div class="job" style="grid-template-columns:1.4fr 1fr 1fr 130px"><div><b>${esc(j.company)}</b><small>${esc(j.source_name)}</small></div><div><b>${esc(j.branch)}</b><small>${esc(j.type)}</small></div><div><b>${esc(j.post)}</b><small>${esc(j.location)}</small></div><div class="actions"><button class="apply" data-pub="${j.id}">Publish</button><button class="notify" data-rej="${j.id}">Reject</button></div></div>`).join(""):"<div style='padding:12px;color:#718096'>No pending AI jobs.</div>";$("#publishedList").innerHTML=d.published.map(j=>`<div style="padding:10px 0;border-bottom:1px solid #edf1f6"><b>${esc(j.company)}</b> — ${esc(j.post)} <small>${esc(j.branch)} / ${esc(j.type)}</small> <button style="float:right" data-del="${j.id}">Delete</button></div>`).join("")}
document.addEventListener("click",async e=>{try{if(e.target.dataset.pub){await api("/api/admin/jobs/"+e.target.dataset.pub+"/publish",{method:"POST"});load()}if(e.target.dataset.rej){await api("/api/admin/jobs/"+e.target.dataset.rej+"/reject",{method:"POST"});load()}if(e.target.dataset.del){if(confirm("Delete this published job?")){await api("/api/admin/jobs/"+e.target.dataset.del,{method:"DELETE"});load()}}}catch(err){alert(err.message)}});
$("#job").addEventListener("submit",async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{await api("/api/admin/jobs",{method:"POST",body:JSON.stringify(o)});e.target.reset();load();alert("Published.")}catch(err){alert(err.message)}});
$("#scan").addEventListener("click",async()=>{try{const d=await api("/api/admin/scan",{method:"POST"});load();alert(d.message)}catch(err){alert(err.message)}});me();